<?php

$title_name = array(
    1 => "นาย",
    2 => "นาง",
    3 => "นางสาว",
);

$cigarate = array(
    1    =>    "กรองทิพย์",
    2    =>    "กรองทิพย์ 90",
    3    =>    "กรุงทอง 33",
    4    =>    "กรุงทอง 90",
    5    =>    "เกล็ดทอง 33",
    6    =>    "เบรก( Break)",
    7    =>    "โบนัส กรีน ( BONUS GREEN )",
    8    =>    "โบนัส เรด ( BONUS RED )",
    9    =>    "พระจันทร์ 33",
    10    =>    "เพลย์ออฟ",
    11    =>    "เพลย์ออฟ (Playoff)",
    12    =>    "รยส.90",
    13    =>    "รอยัลฯ90",
    14    =>    "สามิต 90",
    15    =>    "สายฝน 90",
    16    =>    "เอสเซ่ (ESSE)",
    17    =>    "แอสโตร พรีม่า กรีน",
    18    =>    "แอสโตร พรีม่า เรด",
    19    =>    "ไอสกอร์ (iScore)",
    20    =>    "ไอสกอร์ บลู(iSCORE BLUE BOX)",
    21    =>    "Blue Range",
    22    =>    "Bond Street- บอนด์ สตรีท",
    23    =>    "EUR-GREEN",
    24    =>    "EUR-RED",
    25    =>    "GOAL",
    26    =>    "KRONG THIP 7.1",
    27    =>    "L&M-แอล แอนด์ เอ็ม",
    28    =>    "Marlbolo-มาร์ลโบโร",
    29    =>    "Mevius original blue",
    30    =>    "Mevius sky blue",
    31    =>    "Mevius wind blue",
    32    =>    "Mevius nordic",
    33    =>    "Mevius crystal green",
    34    =>    "Mevius Option",
    35    =>    "SMS  ซองสีเขียว",
    36    =>    "SMS ซองสีแดง",
    37    =>    "Stallion V8  สีแดง",
    38    =>    "Stallion V8  สีเขียว",
    39    =>    "Winston Compact Red",
    40    =>    "Winston Blue",
    41    =>    "Winston Green box",
    42    =>    "Winston Classcic",
    43    =>    "Winston  compact blue",
    44    =>    "Winston  copact green",
    45    =>    "WONDER รสอเมริกัน",
    46    =>    "WONDER รสเมนทอล",
    47    =>    "อื่น ๆ",
);
$alcohol = array(
    1 => "แสงโสม",
    2 => "รีเจนซี่ (Regency)",
    3 => "มังกรทอง",
    4 => "หงส์ทอง",
    5 => "พระยา",
    6 => "คราวน์ 99",
    7 => "เบลนด์ 285",
    8 => "เบลนด์ 285 ซิกเนเจอร์",
    9 => "เมอริเดียน",
    10 => "ดรัมเมอร์",
    11 => "แม่โขง",
    12 => "อื่น ๆ",

);
